### ISSUE TITLE
Selected date is one day previous to clicked day

### ISSUE THREAD

**Issue by gthomas3** [mskocik/svelty-picker#10]
I had thought this was only happening in my local instance but it appears to be within the github.io and REPL.

https://mskocik.github.io/svelty-picker
https://svelte.dev/repl/98fd362aad6049f4b38606820baff0b0?version=3.44.1

*Steps to reproduce*
1. Click the text input to open the picker
2. Select any date (eg Jan 22)
3. The day displayed within the text input is one day previous to the selected day (eg Jan 21)

The incorrect date is bound to the `bind:value` parameter.

**Comment by mskocik** [comment]
Works fine for me. What's your local time settings, I mean timezone?

**Comment by gthomas3** [comment]
Thanks for the quick response. I'm in Eastern Standard Time.

![image](https://user-images.githubusercontent.com/1224054/150374494-3488cf61-519a-4698-9ebd-3767dca1e22c.png)

**Comment by mskocik** [comment]
Okay, will dig into it... But it can take a while, because working with dates in vanilla JS is pure joy 😃

**Comment by bradak1** [comment]
Same for me.  It picks the previous day.  I'm Pacific Time
