### ISSUE TITLE
Problems with 3.5.1  - Error: Failed to resolve entry for package "svelty-picker"

### ISSUE THREAD

**Issue by draew6** [mskocik/svelty-picker#101]
I had to install 3.5.0 back.

Error: Failed to resolve entry for package "svelty-picker". The package may have incorrect main/module/exports specified in its package.json.
--
20:25:18.140 | at packageEntryFailure (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
20:25:18.140 | at resolvePackageEntry (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5)
20:25:18.140 | at tryNodeResolve (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
20:25:18.140 | at Object.resolveId (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
20:25:18.140 | at Object.handler (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46681:19)
20:25:18.140 | at file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:24899:40
20:25:18.140 | at async PluginDriver.hookFirstAndGetPlugin (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:24799:28)
20:25:18.140 | at async resolveId (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:23480:26)
20:25:18.140 | at async ModuleLoader.resolveId (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:23893:15)
20:25:18.140 | at async Object.resolveId (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:7990:10)
20:25:18.164 | Error: Command "npm run build" exited with 1
20:25:18.506 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

**Comment by boczpeter** [comment]
I got similar problem.
Can no longer import my locale from 'svelty-picker/i18n'.

**Comment by mskocik** [comment]
Wrong content (whole repo) was published in `3.5.1`, not just component itself. Sorry for that

**Comment by draew6** [comment]
@mskocik dekuji
