### ISSUE TITLE
HTMLElement Error when trying to import svelty-picker

### ISSUE THREAD

**Issue by rajithaBK** [mskocik/svelty-picker#109]
Hi,
I am just trying to import svelty-picker in y svelte application and I get this error

Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/node_modules/svelty-picker/dist/index.js"
|- ReferenceError: HTMLElement is not defined
    at eval (C:/Users/rkanthet/drs-web-app/node_modules/svelty-picker/dist/utils/custom-element.js:37:29)

does anyone know any fixes for this?

**Comment by rajithaBK** [comment]
attached is the source code, that is producing the error 
https://github.com/rajithaBK/svelty-picker-try-out

**Comment by mskocik** [comment]
Fixed in 4.0.3
