### ISSUE TITLE
Issue with startDate

### ISSUE THREAD

**Issue by MihailZharavin11** [mskocik/svelty-picker#114]
When I set the startDate, in the current month, everything works fine. But why can't I select in the next month the days before our startDate?
[Example](https://svelte.dev/repl/abb61d0e702747f2b598145e234ff56e?version=4.1.1)

**Comment by mskocik** [comment]
Why? Because it's unintented bug! Will fix right away.

**Comment by MihailZharavin11** [comment]
Thank you very much
