### ISSUE TITLE
v4.0.9 - Failed to resolve entry for package "svelty-picker"

### ISSUE THREAD

**Issue by rakshay905** [mskocik/svelty-picker#116]
After upgrading to v4.0.9, getting this issue. Also it is working fine with versions till v4.0.0-beta.1.

Failed to resolve entry for package "svelty-picker". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "svelty-picker" package

**Comment by mskocik** [comment]
Not sure why, it works for me. I've updated the package on Sunday in one of my projects. It works even on [sveltelab.dev](https://www.sveltelab.dev/#code=N4IgdA5glgLlEDsD2AnApiAXKAZlANhtiAMZIIxoUDOWoA1lAgCZYjUBua%2Bl%2BAhgCMAtAFcoADj4gANCAEicONCiwBtACwA2aZvHTxAZmkBOAKz6jARkvbrl6dfUOADPcvOH7z2%2Bcf39sxdjbxc-SwB2Fz1-T3MvdUjjaIiXOOdo3xdpBOzbSzjLDJ9k21dstMj3AtLsyssAJhNE4PdEyucrMvjSty9rDNyXXrC9LWzGrwMjMZjrEcHrc2N2loaooaz%2B1M8eweNV4ZcJ5zTp0rzzGZtt9xau-J2moM9G9UvjzwzqjbH9kLmjjcOgtrosQaU0ndet9ls9rK93i4ALoAXzRsjAAAd0DA4MoUCQ6CA8IQiWQKFQYLRiIwWGxONxeIJRBIpLJ5IplGoGp0TNIDE5rHU0vZxE5YUlYvynKY9AYJqDLIKUjF1IKPMEBVKqp4-MD3EV9L06r1dlrZfyFXlle17GqsprldanjqDTc%2BsDNCa4c5grDzXLGlqAXZdRstfavI6Xp51QUwtpxO00gmXE4A5bssF1KNRuq%2BcG1m6hS5OvGpRn5SZ7IWFerTY9XfcnG8Y8WVfqTmHW2CtrN0o2ylrjNN89H4esS%2B4y2HDBtYY4THcnLp3crzJXGsYay3tMPRw7pf9ChtF2eu%2B49dCjxaq9uHPUjFXg85jmlDWDN0f1K8Lp9TwO1hmi26ZBsqvRWu6hyfjKgYPk%2BYExguSras2N5wYWBQfoBoJDqBD4bhM9RLLyDRpKi6IgJifAkPQfAQGgYAAFbUOQRIkkQoDkpQNBErSrCYOwXA8NwzJiJIMhyAoSgqJgqg8oehYais4awZmmH-v2JQAXoEqjEsunCtsfwRmOR59mhvYXtYYZfhGozaDmgzqNGkYauZRYoa6J7IcB0i3pBZ4dnaZmFrY9QQap-kYeqByhJ47SGqZinrkusbuoFDxfgpUYFuKyTJpOmR2cqXyDjWW4FUCGQeMluXjpkswniVmnWWaxxXv%2BdXueOnn1q1IqeNGAUeWVQHhgqdanieTa9K5ZkNQqvSxS61wtRO54NuNs3pVWrY9kWOHtDOAIHYNyHisu5Txd5%2BFjHtlwFKscblZm90gYe0Z-O4-Xfc4kTrQ8FnFK9Pb-e6e4KnEEVhiZQZynBvYzV0OG7K2f2-XcAMItd20PN9Nkhq%2BQIIc57R-gT0HE02ZwuH%2BoYAi%2BfJkdkoXqp1Wyrk1xxUxzUZ3INMHRZmOU9UemipcDk64T4f45AumTIYFaHo3UdR5DuwvPuKMoeGMTn63KH31eLkvIyD20o3L7SFeNLXGC22baKYesOf5iFuXyvVTU1eQQtN6ZqdrJi64MpiOY5Rus59Hk%2B-cftAstuOHVV07unrBRYTpr326H%2BvZm7LnfgtHlZ1pOdB4hDvu85hdR57fql61Fsy9dGPzlj6HqTr-l2s7v698XMeFmNre5zXYymH3-mB4eLMN%2BZjX3DzYaXtNGoC9NG6V-Bw9m9h2kNHaBRvmlrQB13wfV6YA8G87ANmSzfTEciaIorI1AEkSzBQOgJAwKgAAnkSPgmJMRgAABYwAALb4HYgQTipByA8SpHxJgAkhKMlEsIcSbIpKclkqoTQtUjCrnCMEL0%2BgnDiGCOIDwmhNTHCdD6PQmgPjELTIOO4iMBzIT1KQzWTVaorg%2BBQvUv12j0NEXyDhtxpraH9FuK6F1UINk0IIlUuEcbhyPHtSIbCY6yN9PIp4VYAQKyhDoDRY17irCWulO2%2BFKar1biGa46iPKbzXpbFcPg%2BZlT%2BsfIaQJUw-V0a8fR0jNRGSlu2XY59vIR04TEBWtV2gyL1u0CR8UDEegySYZIfiHwVXir5J4Z1m7S3ieDRJyc44twCJI3Git1ZPA8S%2BcClTFxalyWLIxeos5mKBqCGGxYyjtPZu6E%2B6wFwwxGs4tx8S%2BiKm3joIMMTzZVIArba4vxCk3RhgYfRmSbrWVYdIjh8t9neJhr0nQJywmW24Ws1%2BlF8BQAEN-X%2BaB-5AKJAAYSQCICkKAwAMhEvA0kxBuKUmpAwdB9JhJMhwaySSHIZJqFkfjZ6GVHh3Oeb7TMCzNGpirO014ehTB3EUs7HhaQgyvA3seOopLGgGPJVmbIowSmiy9i6QClldkagUXFKcyzIZTJFi01enYk4M00e%2BYpUqXppzCVMEwjl7BUpjsSlljwyUlNMJEbVuUn56mZtTElZ9cIFEOGY5w4o9XeIFfYShYylid3UHrHlj4dWiqtXbV4Ai3rBBNe5M19zahSgJiqzy2g7leA4ZKMVCd5W1XsQCC0f0Amdw8aLR1Mq9SGjdQKj1LhKgv3xToRKxlO79nTbvXVLjwppGZr6ptizMweO7SUouZLSYGFWP7ORMRB2ZhGmOy2kIt78haC-RNJzk2aNTYTRNxwKJv1kCgIFlA4UgB-n-ABKBgHEAANT8EATusFSLEEcTJMg2FaC6SCXBcilkEl2TSS5HJLFZbzzTPGlWpsdjjzMOfE7KNqqcIBEMusX4qxM6zv8tSy5RkY24sAx8BdqFrlrQiS89wG7ZCnuogxMFyguCgpYpCxBMLeI0gRS%2Bm9-AUUfvwRiuSsx6hhAzV5PD1roLDIle2Rp8UDVEpiaM-mb1vVdtdQy3epqvLxwSg4yYRFeSN3MSpGIE6KEKJiV2OGVCAIgbdGU0d1K53mDDQRZDrz34gBI-RRir7b0IPvRSej8Ln2YJEix99eD0XfqIWEP9ymAPuOkcBtsq6wNsu9GK0JaF7U%2B0JsY8D-JSgBNGPoxLAbXEoSuGXFGh8hyhqs0CMzcX9WNDnLE1GSq6G1vLRfVLamfCMKQ0jA%2BjYYYHVPn9W0u0KubHDV0bjsW5X8bGQ2e1ylHiwls6h6NOLvKQQTfQ8RnKq3hBXmM-ZZjfVrzKbCK4C2R0TY3LyFbYSi6bcjW61dTrCt3UiVkIxyoREfY8PVzZcSmsDLPjUtC2Z3t5KxWy6R4RdgqMZscf1-U7yJFw60oZ1SzO8NaU1Qiq0ahiNMUwhxKM2WCIdY2RUUNhY5ByN4myBNLj03%2B418uekFhL16Ll16I6U545nVqdHq11SdDUZrQIyascyofi8%2BbIQGcghKy3apsHJQzA5-%2BWnrjjEbUl5ba8ZLF3g625BtYvSiMgAgPgJAAg%2BD4DACQage673Qofd5kA-FEVYIC7gtFX7CEWiCr0ObGnDz7UQ%2BfdGKvPVpB3i7LlM97O5TD6hSIkenhDeulPZpksBwjVs9mR6Ke25R9a-tUNPCc%2BjFdtHPacpU93QLvHo52QtWVeT1ZVPBl0-R-8h4EajygYDi9fH%2B0tf%2BT15DSPuvLfE-uXb4PzvBTu%2Bl5s1qivOHsh9%2Br6YD6VYd812b6PxoRr-J7lT630PheO-F%2BXxHmzx-19WSr73%2BP%2B%2Bj81xvuPmvx-jU1nP7PvkefCoG-CUHvUwIwfvcnJ-TfF-JyN-fCOPJyQ-BAyOL-dQC-JPK-BfZOeJSbcaMvLWInaA4fA2O6afd-IuLPQ-DAufLA4Ag6XA1MVsOPSAyvGA0gt6cghAvvDcf-fPa6CpO-bnPA3ZVfQg5JQfZ-Fgilb-U-NAhA4-dZGffgoAlfQcfqS7IJSgx-SQ9g0NA8PaRvJAifPfCAp8PgtvOgtQnxUzH4GzPvHQxVYfaQkfFA%2BQ8dRQtAmgwAqwoQmw-sSxZgtfZVDfZw7fV4BvKfdwvfGUP-ZQyw5Oeg%2BlY8VMPTaQchLpPjLcDZDcbMO6JYOoSaIqIJXsKTb4AI2QzQbLdOVrcINoNKerMo7nYxcIMIQTRyfCMderFGKwdLEpcQcwcIJ8PIzMcQexJdLaGyd-DIhoPwUZWVbsfCAYpfJLCnCfE2ShPhRbOoDQgVPMdSYIVotcQnCwVaMLJDd-MdLmPjHwFMUYowLYz8EYzLPbbOWJG1NKRRdIj8YKC4-CMER4h4QQyyC8YmFQ3w8GMGXjJg6dNNEINIo426E4uolIkIMdd-HnQTa8CcUAjYWzCNRNFaetYybGGAjaZTHwfbPjQvBZaDdKCpduCo3THhC7ZTf-I7TTYWQPY8YTY7MWVQoQyUXEoQ7QkI4g6vCgrgyfYw%2BImOAUyErvYUhUl-Vg0IiUsg6I14UNM-WUk2eUxfIU5oNQrPVU8U1wzgzUzlT-aggAxufUkAo0oQz-U03Qkg-YsfZA8dLfLw20nwxItQw04HRfcA8QgfJw9Ui0z0vfGQm0-ggvf0vw1xEQxyS4cvMU10iMj0kwn-JvCwuUiExfPXB8GElUxwuDTMmM7MuQmU9A30%2BM4EwspMksk0sst0N02QmshAmUcw3U8Nedc1P0a5RqQ5EPE2Wk3DFsRDRklGSxSA1k9UY1SrAk-sh0IcuYn1TkwMjPVVG41TImDOATaWJOfvHyHY9ggsh0oMzPO0bwv0UVOkxcE82DRcEgi8hg08ZMgQ7MW854OHTscsEaO%2BfyGzEXZ4fg9waEx4KE-lLxQCOZRGU8%2Bkg8hs5pSC-An83EwJZtNue8ic0MxCl85C8PZU-wmcuwzlWs-E-sjdN%2BRzNze3cgPACAZiJ3DzF3LzVBBjXzNzb3VFT9AhbkUE6rabCVVJVaZWJOdrbkuRTLCWbUZnMrWWKUeWJpJWbnIrAovcxUGsUbPJGnV4BTOS7aKTFeDkqrKbNTRyWqChfeN4rXa2VrWpdE6eJ7KmU%2BVVF%2BPafDaTOEpGUS-1PUdy4EcTMy01EHb4fvPkvlGnUksStSosl8zSlNNEtCuCnlYZQoiyoKP8IZW1H0Hle4eYJE3y7XQqinS4f4wfHwAq5hPGKnC0GKxytqBXLpFnMoNXfxSDRqenBDKNOKzKhKjS1abHGyKSmrZHKVUeb4NXaK1PUkoYwEI7IPLS-4sqiyAoTpImSxTte1RDIZNo2reSgazyESgCBteVf4qTY0EWKqinao4koZO1bIm6gDMoP6ZInUYzIRAaDrGVba8VWQpGLxa4duR6rS4TXCJHZ6k7Y6pZXcOUua%2B4gCGqu62LGzLnWncKqCpnXrIsjq6aLnOnAIXqlS0pWGi%2BT8Y4XjVaxHCaGoiC0DX87HayJ69PVHQ6-q2LOG5S-HL2VS8mpqHeTm8k7mkgnwNtVtFmfEjmEQ6mw651Sk4arZO8AKwEGmWfc3DgWARickJilimjTzFBPdD3JjL3MSPi9jELGLck06sy3K1qxSpq74I7XHBm6SjLIMGy%2BS3G%2By5Sm2CGE3UeM0XSoHHnOWwNXeWXfsdyj0V1fLQKkmEWTyqm36mSz2n6ossdaWj8njRmiOhWwEZCGtfO9XN26yTqVymVIK6YOYzknXVOf8lxdGolbEhS5onZKymfEcTYF%2BSiu4GioAA).

It must be related to your project setup I guess

**Comment by mskocik** [comment]
Any progress on this?

**Comment by mskocik** [comment]
no feedback... closing

**Comment by mskocik** [comment]
@rakshay905 this has been fixed as @asticode mentioned in #128
