### ISSUE TITLE
Setting Multiple date values/initialDate on isRange

### ISSUE THREAD

**Issue by nicholasvperry** [mskocik/svelty-picker#121]
I am trying to add the inital values on the date range but it seems that this is not possible, not working, or an I just a newb! I would expect doing something like this to get an intial start/end date. 

```
<SveltyPicker
		autocommit={true}
		format={calenderFormat}
		isRange={true}
		initialDate={{new Date(), new Date()}}
		bind:value={testValue}
		on:change={consoleValue}
		inputClasses="dark:bg-gray-700 dark:text-white border p-2"
		placeholder="Select Date"
	/>
```

**Comment by nicholasvperry** [comment]
So after I tried for an hour, I wrote this issue and then as soon as I did I figured it out. Here's how for the next noob like myself...
<SveltyPicker
		initialDate={[new Date(), new Date()]}
	/>

**Comment by mskocik** [comment]
Nice! Yes, array must be passed for date-range As I can see, this is missing in the documentation. I will fix it right away!
