### ISSUE TITLE
v3.5.0 bind:value returns null if click on selected date

### ISSUE THREAD

**Issue by Hmerman6006** [mskocik/svelty-picker#123]
When I bind a variable to the picker that has a set value, the on change function returns null for bound variable if I  click on the selected date.  If I click on a different date all is well.  Is this behaviour normal?
```
<SveltyPicker inputClasses="form-control mt-0 fs-14" format="yyyy-mm-dd" bind:value={sDate} on:change={getDate}/>
<script>
let sDate = "2023-08-23";
function getDate(e) {
    let form = {
        date:sDate // this is null if I click on the 23rd of August 2023 which the selected date, but return correct date otherwise 
    }
}
</script>
```

**Comment by mskocik** [comment]
Yes it's normal, if you want to disable it set `clearToggle={false}` property
