### ISSUE TITLE
endDate doesn't seem to be reactive

### ISSUE THREAD

**Issue by asticode** [mskocik/svelty-picker#128]
Hi 👋 

And thanks for this awesome svelte component!

I'm using the `endDate` attribute and I want it to be reactive (I have 2 datetime pickers, and once I select a value in the first one, I want the `endDate` in the second one to be updated), however it doesn't seem to be reactive.

Is it something desired?

Cheers
Quentin

**Comment by asticode** [comment]
I was not using the latest version since I had the same issue as [this one](https://github.com/mskocik/svelty-picker/issues/116) but when using the latest version it works properly.

However, to fix the error `Failed to resolve entry for package "svelty-picker". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "svelty-picker" package` I needed to add `"default": "./dist/index.js",` to the `exports > .` key in the `package.json`. Would you be open to make that change in the `package.json`? I could make a PR if you prefer.

**Comment by mskocik** [comment]
Thanks for pointing out the issue with `exports` definition - I added it and released new version (4.1.3).

**Comment by rakshay905** [comment]
Thanks for the update, will try it

**Comment by asticode** [comment]
Everything works like a charm for me ❤️
