### ISSUE TITLE
Set Label for input element 

### ISSUE THREAD

**Issue by mugu-fatman** [mskocik/svelty-picker#135]
How to set the label for input element, tried to using name property but doesn't work or I don't want to use placeholder. "DateTime-local" should be displayed on top of the input 

![image](https://github.com/mskocik/svelty-picker/assets/62667193/b3a7c937-d020-46dd-b67f-6a34c1b3e7cc)

**Comment by mskocik** [comment]
It's up to you. Because SveltyPicker is just wrapped in `<span>` element, you can use any HTML you want

**Comment by mugu-fatman** [comment]
Sorry Probably I was not clear with my question , I was able to add Due Date label to SveltyPicker , but I would need something like the input fields Reporter and Assignee as shown below 

![image](https://github.com/mskocik/svelty-picker/assets/62667193/7d1f6cd1-78b1-4040-92f3-d522b81f8e9c)

**Comment by mskocik** [comment]
And how does the markup looks for those Reporter, Assignee inputs?

**Comment by mskocik** [comment]
Then you must recreate the same logic by providing custom content for `inputs` slot. Check docs for slots for more info and example.

**Comment by mugu-fatman** [comment]
Got it thanks

**Comment by mugu-fatman** [comment]
> Then you must recreate the same logic by providing custom content for `inputs` slot. Check docs for slots for more info and example.

Thanks
