### ISSUE TITLE
Add support for hourOnly option

### ISSUE THREAD

**Issue by dreinert1994** [mskocik/svelty-picker#136]
I just recently started using Svelte for a client project and I am really loving it. We have a need in that project for a date picker and, after much searching, I came across this library and I am really loving all it can do out of the box and how effectively I can customize it for our use cases. One thing I was hoping to add though is around the time portion of the datetime selection UX. We have some use cases where we want a user to select a date-time to the _hour_ but do not require any further specificity. I was hoping to add a flag to support this that would effectively hide the minute portion of the UX. I cloned this repository already and started to make the necessary changes but I don't believe I am able to open a PR, so I wanted to raise it here as well.

**Comment by mskocik** [comment]
Feel free to open that PR. Can be useful for some.

**Comment by mskocik** [comment]
v5 released with `hourMode` - I did some visual tweaks to time view in hour mode. Thanks for PR 👍
