### ISSUE TITLE
End date calendar for range does not show the selected end date by default when you open the calendar

### ISSUE THREAD

**Issue by whishkid** [mskocik/svelty-picker#144]
if you specifiy a range for the calendar of more than 2 months (e.g. 1 jan 2023 - 5 may - 2023) and then Toggle the calendar view, the calender on the right side will always show ' Next month (today + 1 month) instead of showing the month that contains the end date.

IMHO this is not desired behaviour. I have already inspected the code and can submit a one liner PR Fix for this if you allow me to push a branch/PR

otherwise the change should be here
in: https://github.com/mskocik/svelty-picker/blob/main/src/lib/components/Calendar.svelte
line # 8-89
instead of
____
 let activeDate = wid === 1
    ? (() => { const d = new Date(dates[0] || new Date()); d.setMonth(d.getMonth()+1); return d })()
    : new Date(dates[0]?.valueOf() || new Date());
______

should read
_______
 let activeDate = wid === 1
    ? (() => { if(dates[1]!=null) return dates[1];const d = new Date(dates[0] || new Date()); d.setMonth(d.getMonth()+1); return d })()
    : new Date(dates[0]?.valueOf() || new Date());
_______

**Comment by whishkid** [comment]
if you want me to make a PR please let me know if this can be default behaviour, or if it should be depending on a paramter flag

**Comment by mskocik** [comment]
Not sure why my comment wasn't sent (I sent it through the email) ... I wondered where is the PR 😄 
I will add it right now

**Comment by whishkid** [comment]
Maybe I did something in the wrong way but I was not allowed to create a branch so I don't know how to create the pr then

**Comment by mskocik** [comment]
Nevermind, I did it myself. It was great that you provided all code needed :)

But in general for creating PRs you need to fork the repository and do changes there and after you push your changes, github will show you a button, that you can create PR for upstream repo.
