### ISSUE TITLE
calendar wrapper

### ISSUE THREAD

**Issue by Vichondrias1** [mskocik/svelty-picker#148]
How to fix this when I try to add svelte picker on a container in tailwind the calendar doesnt go outside the container.

![image](https://github.com/mskocik/svelty-picker/assets/39474726/8dacc37f-9a5b-441e-820f-a02765b4c0f9)
![image](https://github.com/mskocik/svelty-picker/assets/39474726/85e9844c-0944-4e2b-bdc7-842d52f0eb25)

I was expecting the calendar to be like this.
![image](https://github.com/mskocik/svelty-picker/assets/39474726/63ae9f1b-4cc7-481e-8d55-769f16084cae)

**Comment by mskocik** [comment]
Before `5.2.0` it's not possible to fix.

In `5.2.0` I added new property `positionResolver` where you can pass your own floating position resolving function. Svelty-picker uses [floating-ui](https://floating-ui.com) itself, so you can use it for your own resolver. It already provides [detectOverflow](https://floating-ui.com/docs/detectOverflow) function, which will be required to handle your use case properly.

**Comment by Vichondrias1** [comment]
> Before `5.2.0` it's not possible to fix.
> 
> In `5.2.0` I added new property `positionResolver` where you can pass your own floating position resolving function. Svelty-picker uses [floating-ui](https://floating-ui.com) itself, so you can use it for your own resolver. It already provides [detectOverflow](https://floating-ui.com/docs/detectOverflow) function, which will be required to handle your use case properly.

can u give example how to use that new property you added?

**Comment by mskocik** [comment]
> can u give example how to use that new property you added?

Just like any other prop:

```svelte
<script>
function myPositionResolver(node) {
  // your code
}
</script>

<SveltyPicker positionResolver={myPositionResolver} />
```

If you have no idea how the resolver should/could look like, check the built-in position resolver:

https://github.com/mskocik/svelty-picker/blob/8b1061b7fc31e8da9c56e0ab65e441d1b73ab2a1/src/lib/utils/actions.js#L1-L33

And build your own on top of it with detectOverflow helper function etc.

**Comment by Vichondrias1** [comment]
> ```svelte
> <SveltyPicker positionResolver={myPositionResolver} />
> ```

is it neccessary to add positionResolver function to fix my problem or the build in function you added should fix problem it and i dont do anything?

**Comment by mskocik** [comment]
> is it neccessary to add positionResolver function to fix my problem or the build in function you added should fix problem it and i dont do anything?

Yes, it is neccessary to add positionResolver for your use case

**Comment by mskocik** [comment]
@Vichondrias1 were you successful with implementing your own resolver?

**Comment by Vichondrias1** [comment]
![image](https://github.com/mskocik/svelty-picker/assets/39474726/7baac5ee-b260-48a2-b618-6e7412d7a3d6)
i havent figure it out how to use it can you please help me how solve this? dont quite understand sa how to fix this 

![image](https://github.com/mskocik/svelty-picker/assets/39474726/0ed51e04-3a3d-4208-bfe1-070abd612201)

**Comment by mskocik** [comment]
I gave you all information you need. 

My time is precious so I can't help you _for free_. I believe you understand.

Anyway I am closing this one as root issue - ability to customize position resolver is fixed now.
