### ISSUE TITLE
Month selection off by one month

### ISSUE THREAD

**Issue by bradak1** [mskocik/svelty-picker#15]
Open the Picker Control. Select the Month-Year at top.  Select July, then pick the first day.  It closes and shows the date of:
2022-06-01.  It should be 2022-07-01.
I can reproduce this on the Repl as well.

It works correctly if I pick any other day.  Only occurs when you select the 1st day.

**Comment by bradak1** [comment]
I can also see this by changing the month with the Up/Down arrow at top.

**Comment by mskocik** [comment]
Looks like another bug with timezone offset. Because it works fine for me
