### ISSUE TITLE
When selecting the same day, hour selection behavior is strange

### ISSUE THREAD

**Issue by Arenz2001** [mskocik/svelty-picker#157]
When I select the same day in the picker, the first hour i choose goes into the second slot (so the end hour). I don't have this issue when I do it on multiple days.

I don't know if it's an options but I don't think so

![picker bug github](https://github.com/mskocik/svelty-picker/assets/62725768/0a4bc508-c93c-44a2-8216-00ae6b78fb32)

**Comment by mskocik** [comment]
@Arenz2001 Are you still experiencing this? I can't reproduce it on the website

**Comment by Arenz2001** [comment]
Still experiencing this. I don't know what can cause this

**Comment by mskocik** [comment]
@Arenz2001 Are you experiencing this also on https://mskocik.github.io/svelty-picker/ website?

**Comment by whishkid** [comment]
Yes i see it on svelty picker site also
![image](https://github.com/mskocik/svelty-picker/assets/895085/eb980fdf-99c3-4a36-963a-ce1943fd1686)
