### ISSUE TITLE
1.2.3 Dependency optimization failure

### ISSUE THREAD

**Issue by gthomas3** [mskocik/svelty-picker#16]
After installing 1.2.3 and restarting the dev Vite server, I get this error:

![image](https://user-images.githubusercontent.com/1224054/150996261-d724160f-9bda-44fd-bbee-5ec8585916a6.png)

Steps to reproduce:
1. `npm install svelty-picker`
2. `npm run dev` (`run-p watch:* vite`)

Using version 1.2.2 the dev server starts as expected.

**Comment by mskocik** [comment]
Fixed by reverting related commit

**Comment by gthomas3** [comment]
Thanks for your quick fixes!
