### ISSUE TITLE
Library needs to be updated to allow svelte-5

### ISSUE THREAD

**Issue by whishkid** [mskocik/svelty-picker#170]
In my projected in  a test branch i updated to svelte 5.. but I think this library needs some work to prepare.

Should update peer dependencies to 
  "peerDependencies": {
    "svelte": "^3.53.0 || ^4.0.0 || ^5.0.0"
  },
  
  But i think you also need to update to latest SvelteKit first

**Comment by mskocik** [comment]
PeerDependency updated in `5.2.7`. I as quickly tested basic functionality it should work.

**Comment by whishkid** [comment]
Did you run te test project using svelte 5 ? Didnt seem to work for me, but i Have bigger issues with the svelte 5 upgrade, so for now just replaced the datepicker with SHOW DATE HERE :)

**Comment by mskocik** [comment]
> Did you run te test project using svelte 5 ?

Of course 😃 whole library works in dev mode svelte 5, but doesn't build. But it's not related to component itself, but some other dev dependency.

As you can see in this [svelte 5 repl](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAClWQ3UrEMBCFX2UIQndRd1UQoaZF30DYS-tFm04xmCYhmSyUbt7dJAV_rsKcOd_JSVY2SYWe1e8r0_2MrGav1rIbRovNgz-jIkyzN8GJrHAvnLTUdrojOVvjCE7ZtLxJ8YUOJmdmqAq33NqivTweHg5P1XNGFBIIEzRBA1eeesLd3T5v0m4KWpA0GqQWDmfUtNvDmjcdbcx1A_clJm5ETjv3KmAS-fG3meZDIEpJRguVOjTrT2QszYvqa1hLbsz0Rmz0pyvnCRUKwhHG1DOZy1VwuUCljcYq8iH7-L_3D1KPdTG2_Ph306ZfnM0oJ4kjq8kFjB_xGyPgTXiAAQAA), it works. So probably something else is breaking your app and not the svelty-picker itself.
But to be honest I haven't done more deep testing myself. So if you find some bugs with this transitional version, let me know.
