### ISSUE TITLE
Getting the following error qn.minuteSwitch is not a function

### ISSUE THREAD

**Issue by isAlmogK** [mskocik/svelty-picker#172]
Hi, we are using the svelty picket in our app, and we are running into an edge case where the app crashed. Further debugging this, we see it is something within the picker 

**qn.minuteSwitch is not a function**

Seems to be happing here 

```
case "Enter":
        isFocused && e.preventDefault();
        if (currentMode === "time") {
          if (!timeEl.minuteSwitch(null)) {
            return timeEl.minuteSwitch(true);
          }
          return resetView();
        }
        if (isFocused && resolvedMode === "date") pickerVisible = false;
        if (innerDate && resolvedMode.includes("time")) {
          currentMode = "time";
        }
        break;
```

**'timeEl' variable is the Time element that's used in<Time /> Component. Looks like because of timing issues 'timeEl' is not being loaded in time and that's why we can't access it's function**

**Comment by mskocik** [comment]
What version of svelty-picker are you on? There is no such code on the latest version.

**Comment by isAlmogK** [comment]
"svelty-picker": "^3.6.1",

**Comment by mskocik** [comment]
Try to update first, at least to v4 (which is the version, where this has been rewritten)

**Comment by isAlmogK** [comment]
Well do and update you

**Comment by mskocik** [comment]
Since we are on v6 (svelte 5 ready) there is no plan to support older versions
