### ISSUE TITLE
Time picker UI not reflecting actual element value

### ISSUE THREAD

**Issue by Simopich** [mskocik/svelty-picker#174]
Hi, first of all, thanks for the great library!

I've just encountered a problem while using the time picker.
I have a variable bound to the picker element that has value "02:25", so the UI shows something like this:
![UI Before](https://github.com/mskocik/svelty-picker/assets/36771527/86855659-78c0-4764-a626-2d25a61f79ea)

Now, if I change the hour to, let's say, "11", the UI changes to become like this:
![UI After](https://github.com/mskocik/svelty-picker/assets/36771527/42acddb2-ed54-4b0f-a53f-bbb0340d7990)

It already shows the minutes as selected, so the users could think that the current variable value is "11:25", but it's not!
It's still "02:25" until you select the minutes again, so you'd need to press the already selected minute "25" if you want to actually update the variable value.

I think the most logical option would be a variable update when you change the hour too, but let me know what you think!

Thanks again,
Simone.

**Comment by mskocik** [comment]
Can you past simple example in REPL?

**Comment by Simopich** [comment]
Sure, I just noticed that this happens only in pickerOnly mode.
[REPL here](https://svelte.dev/repl/b764f3089eea458889738bcb9c61fab1?version=4.2.17)

**Comment by mskocik** [comment]
When you set `autocommit={false}` then the behaviour is clear, because you need to press `OK` button to confirm new selection. Without it... it's probably bug, but I thought I consider this use-case as well. Will need to look into it deeper. And hopefully I will remember, why it's done the way it is 😄

**Comment by Simopich** [comment]
I may have found another bug that seems to be related to this in the time picker with the following options: pickerOnly, isRange, autocommit set to false.

If you choose an hour (hour only, no minutes selected) in the first time picker greater than the second one and press OK, the UI shows a completely wrong state that doesn't reflect the variable value.

Example:

I've set the initial picker value to: ["02:25", "16:40"]
![UI](https://github.com/mskocik/svelty-picker/assets/36771527/acc46928-26d3-4b07-beda-6ebdbc995b42)

If you press "17" in the first picker and click OK, the UI shows "40" as the selected minute in the first picker but the actual variable value becomes "17:25", which I think is inconsistent (And the same thing automatically occurs in the second picker, the hour changes in the UI because the first time can't be greater than the second one but the actual variable value stays at "16:40").
![UI](https://github.com/mskocik/svelty-picker/assets/36771527/462cecbc-61eb-49c5-b4cc-5ced7abf6879)

What do you think?

[REPL](https://svelte.dev/repl/a0a26b9a2a49412d8d693dba9f819947?version=4.2.17)
