### ISSUE TITLE
Exported optional null types have incorrect typescript type in the downloaded NPM package

### ISSUE THREAD

**Issue by jchen42703** [mskocik/svelty-picker#175]
# Problem Description

For example, for the `SveltyPicker`:

When optional null types are exported using JSDoc like:

**SveltyPicker.svelte**

```js
  /** @type {string|string[]|null} */
  export let value = null;
  /** @type {Date|Date[]|null} */
  export let initialDate = null;
```

The resulting typescript types are:

**SveltyPicker.svelte.d.ts**
```ts
 value?: string | string[];
 initialDate?: Date | Date[];
```

**These are not the same types at all!** The JS type assumes that the type is optional and defaults to `null` BUT the typescript example assumes the values default to `undefined`.

This has been the cause of a copy nasty validation bugs on our end because the type checker incorrectly tells you to change your default value to undefined, which causes our `optional` checks to fail.

## Solution

No clue why the type exporter does this tbh...

**Comment by mskocik** [comment]
Check the latest (v5.2.11) version with corrected types
