### ISSUE TITLE
Version v5.2.10 ruined selection.

### ISSUE THREAD

**Issue by AntonPavlenkov** [mskocik/svelty-picker#179]
When updated to latest and using svelte 5 latest. Clicking on day element is not selecting the day.

If I recall correctly what is causing it is  ce_displayElement.onclick = onInputClick; when it should be  ce_displayElement.onclick = () => onInputClick();

Because it is only thing that changed from 5.2.9 to 5.2.10 that do some actions

**Comment by AntonPavlenkov** [comment]
Yeah on 5.2.9 was working fine. But we found that we could tweak some code to make it work. So I guess we did not integrate correctly from the beginning. Sorry for trouble.

**Comment by mskocik** [comment]
Just to clarify, the `ce_displayElement` is used internally for customized custom-element version. But probably no one is using it except of me :)
