### ISSUE TITLE
6.0.0 console.log

### ISSUE THREAD

**Issue by akb5566** [mskocik/svelty-picker#182]
1. In the 6.0.0 version, SveltyPicker seems to be printing debug `console.log()` to dev console. 

2. I think the [Working with dates](https://svelty-picker.vercel.app/working-with-dates) doc page can use some example. e.g. I'm doing the following binding, is this the correct/intended way or am I doing some wrong? I don't know because there is no example.

````
import SveltyPicker, { formatDate, parseDate } from 'svelty-picker';
import { en} from 'svelty-picker/i18n';


<SveltyPicker
  mode="date"
  format="yyyy/mm/dd"
  bind:value={
    () => {
      return formatDate(date, 'yyyy/mm/dd', en, 'standard');
    },
    (v) => {
      date = parseDate(v, 'yyyy/mm/dd', en, 'standard');
    }
  }
/>
````

Thanks you.

**Comment by mskocik** [comment]
You are right, the function binding example was linked only in migration guide, I've added example based on your code
