### ISSUE TITLE
weekStart - prop vs config

### ISSUE THREAD

**Issue by LaughingBubba** [mskocik/svelty-picker#183]
Hi, thanks for this great component. I found a problem.

When `weekStart` is defined as a prop, the calendar headings are "mangled". When defined as config, they are not.
![image](https://github.com/user-attachments/assets/997cdce5-0994-40ae-b071-5cddffa6d962)

See my example at the [REPL](https://svelte.dev/playground/99126d5f92fe4c929a1bc30be7d97f62?version=5.14.0). 

In the example, the initial state is the error state. If you uncomment line 18 and delete line 35 the component works as expected.

**Comment by LaughingBubba** [comment]
OK thanks. That explains the same behaviour as `inputId`.

**Comment by mskocik** [comment]
Not sure what you by mentioning `inputId`. That one should be string as html `id` always is.

**Comment by LaughingBubba** [comment]
NVM. I restarted vite as it had been running for hour and I couldn't recreate the problem. So strike that last sentence.

**Comment by mskocik** [comment]
Good good :) report any issue you will find, there can possible some, after svelte 5 refactoring.
