### ISSUE TITLE
The next (down) arrow skips a month if the date is the last day of month.

### ISSUE THREAD

**Issue by bradak1** [mskocik/svelty-picker#23]
![image](https://user-images.githubusercontent.com/4602081/151885600-6d570374-3174-4337-beeb-7d187e257c94.png)

If I click the down arrow here, it moves to March and skips February.
![image](https://user-images.githubusercontent.com/4602081/151885697-c6a81545-a09f-41fd-911c-9599ba385a9a.png)

**Comment by mskocik** [comment]
This will take a little longer to fix... I am quite busy at the moment.
