### ISSUE TITLE
Question about format IN / OUT

### ISSUE THREAD

**Issue by arjarn** [mskocik/svelty-picker#27]
Hi,

I wanna  display "dd MM yyyy" format in your control.
So attempt : 

```

<script>
  import SveltyPicker from 'svelty-picker';

  let myDate = '25 December 2022';
</script>

<SveltyPicker inputClasses="form-control" format="dd MM yyyy" bind:value={myDate}></SveltyPicker>
```

But it fail :-/
Is it possible having this result with standard i18 and custom i18 definition  ?

**Comment by mskocik** [comment]
This seems like a bug when handling initial value...

**Comment by arjarn** [comment]
Working perfect !
Thanx for your great work.
