### ISSUE TITLE
The today tag indicator does not correspond with today date.

### ISSUE THREAD

**Issue by bllaw** [mskocik/svelty-picker#28]
I am at GMT+0800.

I realised that the the today tag was late (placed on the day before) from 12am to 8am. After 8am the today tag would be placed on the correct date. ("svelty-picker": "^1.2.4")

![image](https://user-images.githubusercontent.com/6741049/167309366-b49ad235-2801-4568-bb6f-663909bf62fc.png)
Today date is 2022-05-09 (2:00am), the tag is on 2022-05-08.

**Comment by mskocik** [comment]
Yes, the date manipulations will require some tweaking apparently 🙄
