### ISSUE TITLE
Styling Calendar with `theme` prop

### ISSUE THREAD

**Issue by ehildebrandtrojo** [mskocik/svelty-picker#31]
I'm trying to make a dark-theme version of your calendar. When I try to edit the `theme` prop, e.g. to change the background color (`theme="bg-base-100"`), the calendar becomes transparent and does not seem to apply the css styling. I did this with the button and input classes and it worked. I was wondering if you had any examples of changing the `theme` prop?

Apologies if this seems really basic, still new to frontend-dev.

**Comment by mskocik** [comment]
Check the `docs.svelte` file. There is one example of style override.

Basically `theme` prop is used for your css class which defines all css variables you want to override.

Hope that helps.

**Comment by ehildebrandtrojo** [comment]
Thank you! Didn't see the `docs.svelte` file, super helpful.
