### ISSUE TITLE
format string of Z

### ISSUE THREAD

**Issue by wangjia184** [mskocik/svelty-picker#34]
```
<SveltyPicker format="yyyy-mm-ddThh:ii:ssZ" bind:value={period.startTime} clearBtn={false}></SveltyPicker>
```

It is expected to receive `2021-12-31T15:15:00Z`,  but I get `2021-12-31T15:15:00GMT+08:05:43`

The [document ](https://github.com/mskocik/svelty-picker#format-settings) does not mention `Z` is a special letter

I tried to escape the letter by `yyyy-mm-ddThh:ii:ss[Z]` `yyyy-mm-ddThh:ii:ss\\Z` `yyyy-mm-ddThh:ii:ss\\\\Z`
None works.

**Comment by mskocik** [comment]
Currently that's a bug and it's being worked on.
