### ISSUE TITLE
ReferenceError: HTMLInputElement is not defined

### ISSUE THREAD

**Issue by bokunodev** [mskocik/svelty-picker#44]
idk why but just recently my sveltekit project broke. updating dependencies and using master branch didn't help.
i'd like to work on this if anybody know, what cause it?
```
ReferenceError: HTMLInputElement is not defined
    at /node_modules/.pnpm/svelty-picker@2.1.2/node_modules/svelty-picker/custom-element.js:30:15
    at async instantiateModule (file:///home/smkti/Public/go-sandbox/dhugie-gui/node_modules/.pnpm/vite@3.0.5/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:50457:9)
```

**Comment by mskocik** [comment]
Can you provide demo repo with this issue?

**Comment by mskocik** [comment]
Okay, I was able to fix it, also the error about SveltyPicker types. Hopefully it's good now also for you.
