### ISSUE TITLE
Restrict Minute Increments

### ISSUE THREAD

**Issue by harrisKAsher** [mskocik/svelty-picker#46]
Hi, awesome date/time picker for svelte! Best one I have found by far. 

I was wondering if it would be possible to make it so that the minute picker could be restricted to only every 5 minutes? (So 0, 5, 10, 15, so on). Others might find it useful to restrict to every 10, 15, or 30 minutes. My use can would work with every 5. If not all is good, thanks again for making such an awesome simple to use library!

**Comment by mskocik** [comment]
Keyboard navigation is restricted to 5 minutes steps :) Actually it would be very simple to add. 
If new function property was added to `Time.svelte` component to line 278. Before `setMinutes`, where you could manipulate passed value.

If you want this funcionality, feel free to prepare PR for it.

**Comment by harrisKAsher** [comment]
Awesome, I have created a PR.
