### ISSUE TITLE
"change" event is repeatedly fired for no good reason

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelty-picker#57]
Time picker behaves a bit weirdly - the change event is being re-fired on a fixed interval.

 _Probably due to miliseconds being different from the last date ?_

**Reproduce steps:**
- change to time picker (top right icon)
- press left mouse button and move a bit
- stop moving but keep the mouse button holding
- "**change**" event is being fired repeatedly

REPL latest version
https://svelte.dev/repl/1448a9019bb7481c8d19c605aa190b33?version=3.44.1

**Comment by mskocik** [comment]
Was unable to reproduce this without mouse movement 🤔 no event firing repeatedly

**Comment by FluffyDiscord** [comment]
> Was unable to reproduce this without mouse movement 🤔 no event firing repeatedly

Sorry, forgot to mention. This issue is only on chrome (105.0.5195.127), firefox (107.0a1) seems to be fine.
