### ISSUE TITLE
Timepicker - Change from hour to minute section only when "mouseup" is fired 

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelty-picker#58]
Right now whenever "valid hour is selected" (basically on click anywhere) it immediately switches from hour selector to minute selector, even when user still holds the mouse button. 

Can we get an option to switch from hour to minute selector once when "mouseup" is fired and not immediately ?

**Comment by mskocik** [comment]
Yes, this would be correct behavior
