### ISSUE TITLE
How to get value once when selector close?

### ISSUE THREAD

**Issue by jorgnyg** [mskocik/svelty-picker#68]
Want to automatically update date when the datetime selector close at final step (selecting minute).
Currently firing event on every step (date, hour, minute). Any way to prevent this, and only get event trigger when the selector is closing after choosing minute?

**Comment by mskocik** [comment]
This is not possible at the moment.

There was PR related to this functionality, but it wasn't complete (handling all cases) and thwn another event was added which I didn't like. And when I required rework, author closed it.
You can try to finish it yourself.

**Comment by tbydza** [comment]
Hello,
@jorgnyg I have similiar issue  (#94) and I have created PR (#95)  for it.
I think it is useful for your use-case too.
