### ISSUE TITLE
Calendar cannot be scrolled

### ISSUE THREAD

**Issue by risalfajar** [mskocik/svelty-picker#74]
There's one week missing from the calendar, but it can't be scrolled.

![image](https://user-images.githubusercontent.com/28381124/209609645-1fe9159e-4483-4e9d-8938-4d92e17c004d.png)

I think it's because in `Calendar.svelte`, `.sdt-calendar` has `overflow: hidden`

**Comment by mskocik** [comment]
Calendar display correctly on github page (means date logic is correct)
![image](https://user-images.githubusercontent.com/25513620/209641749-dd92cf91-390e-4a88-acfe-edd4f8cc407d.png)

Cause of your issue must be with your custom CSS

**Comment by risalfajar** [comment]
If I remember correctly, you set the height of `.sdt-calendar` to around 200px. Maybe it isn't responsive enough?

**Comment by mskocik** [comment]
At this point, height is fixed due to scroll animation in year and decade view.

**Comment by risalfajar** [comment]
I think my global style is messing the calendar since it's using a `table`. Sorry, closing this.
