### ISSUE TITLE
Disable Keyboard on Mobile

### ISSUE THREAD

**Issue by harrisKAsher** [mskocik/svelty-picker#78]
On mobile the keyboard pops up by default. When clicking on svelty picker since it is an input. This is not always desirable. It would be nice if we can have a way to disable this. All that is needed is to set the input mode to 'none'. 

There is a work around: Set the  inputId on svelty picker and then on mount do this:
`document.getElementById('inputId').inputMode = 'none';`

**Comment by mskocik** [comment]
Good point, will add by the end of the weekend 👍
