### ISSUE TITLE
[Feature Request] Start in Time Picker

### ISSUE THREAD

**Issue by harrisKAsher** [mskocik/svelty-picker#79]
It would be nice to have a mode where when the user opens the date/time picker it opens straight to the time picker but the date picker is still available to access. This would be useful for when the date of an event is assumed to already be known but the time is not, but on the off chance the date is wrong then it can still be accessed for editing.

Just to be clear, I am not asking for the time to be chosen before the date, I am just asking for a way to open straight to the time picker while still having access to the date picker.

**Comment by mskocik** [comment]
I was thinking about this few days ago, that it would nice to have (and not only for time view, but also for year and decade)

**Comment by harrisKAsher** [comment]
@mskocik I updated to 3.4.0 and tired 4.0.0-alpha.4 and can't get this to work on either. I checked the package and can confirm startView is in there, and I even copied the code from the repl (which is working for me) and it still doesn't work on my app. I am not sure how the repl works but it seems something is not working.

**Comment by mskocik** [comment]
Have you tried to remove node_modules/.vite directory?

**Comment by harrisKAsher** [comment]
That fixed it. Thank you!
