### ISSUE TITLE
Incorrect Positioning of Picker

### ISSUE THREAD

**Issue by harrisKAsher** [mskocik/svelty-picker#80]
On smaller screens the positioning of the picker can be a big deal. I have run into a situation where it is braking on some smaller mobile devices. Here are two REPLs.

This first one breaks on iPhone SE (375 x 667)
https://svelte.dev/repl/76ece399cb7b4284a215a3a061de9c83?version=3.44.1

This second one breaks on Pixel 5 (393 x 851)
https://svelte.dev/repl/7476a4e225734cecb9cc9303e1d7e49c?version=3.44.1

In both cases if the calendar goes up instead of down. I couldn't reproduce it with the time I have in a REPL but I have had it do the opposite where it is going down instead of up. 

I think a simple quick solution would be options on where it is positioned, such as auto (what is now), above, below, or center would be nice so we can manually set the placement for situations where it breaks we can force a fix really easily. That being said, the underlying code to how it works now definitely has a problem because there is no way the iPhone SE one should be going up in that positioning.

**Comment by mskocik** [comment]
Problem is present in v4 version, which was accidentally (lack of my knowledge about npm) published as latest. Latest stable version works fine.

And for v4 this needs to be fixed.
