### ISSUE TITLE
Adding custom inputs/buttons

### ISSUE THREAD

**Issue by nicholasvperry** [mskocik/svelty-picker#82]
I am upgrading my MVC app and was able to add input/buttons to the bottom of the calendar. It would be nice if we could somehow add our own buttons or inputs to the bottom of the calendar. 

![image](https://user-images.githubusercontent.com/90103179/215127310-006c7982-d128-4461-9422-5cda5cd2cf25.png)

![image](https://user-images.githubusercontent.com/90103179/215128234-16cc71b3-31d6-4b85-be78-cd422592f703.png)

**Comment by mskocik** [comment]
You can use pickerOnly and create wrapper component, that will include your custom buttons. Of course you need also to implement positioning etc.

**Comment by mskocik** [comment]
This could be probably added in v4
