### ISSUE TITLE
Feature request: minTime and maxTime in time picker

### ISSUE THREAD

**Issue by notramo** [mskocik/svelty-picker#92]
It would disable the times outside of the range. Both would be optional.

**Comment by notramo** [comment]
@mskocik Could you provide an example?

**Comment by mskocik** [comment]
Use the playground on the website. You can test it there with 'Start 
Date' and 'End Date'. Also set format type to some 'time only'

**Comment by mskocik** [comment]
You can check the example about disabling dates in the docs website
