### ISSUE TITLE
Disabled buttons on time picker should have disabled color.

### ISSUE THREAD

**Issue by valerio-pescatori** [mskocik/svelty-picker#96]
https://github.com/mskocik/svelty-picker/blob/898c9dd3e4506750e6c8527bd99c4b4125028e79/src/lib/components/Time.svelte#L474-L476

Right now the `disabled` state for the time picker only adds `cursor: not-allowed`, it should also add a reduced opacity or a grey text color. It makes the ux very difficult on mobile devices, as there is no way of understanding what is 'clickable' and what isn't other that going for a try.

can I open a pr?

**Comment by mskocik** [comment]
Sure, go ahead
