### ISSUE TITLE
Manuel text input

### ISSUE THREAD

**Issue by Conni2461** [mskocik/svelty-picker#97]
First of all thanks for the DateTime picker its been really useful.

Is it possible to have a manuell text input. I skimmed the documentation and haven't found anything.

So idea is that you can still use the keyboard to enter a date.

**Comment by mskocik** [comment]
This could/should be achieved by wrapper component and using svelty-picker with `pickerOnly` prop. Also date manipulation functions are exported.

It would be hard to implement directly in current component design.

**Comment by Conni2461** [comment]
hmm okay, thats what i thought, just wanted to make sure i haven't missed something in the documentation.

Other question, are there any plans to support that in the future? because right now, if you have a form, which e.g. creates a person with a birthday, someone either has to be aware of the keyboard movements (which isn't always the case for users) or they have to move to the mouse which isnt great if they have to do that (or similar tasks) multiple times a day

**Comment by mskocik** [comment]
I think it would be great addition, but still it would be added as separate wrapper component. It makes sense and v4 dev branch has some code changes suitable for it. But I can't give you any time estimates. I have no free time (read unpaid) for it right now. If you would be willing to pay for it, it could get priority. And also PRs is always welcome
