### ISSUE TITLE
Custom trigger

### ISSUE THREAD

**Issue by jamess-ais** [mskocik/svelty-picker#98]
Hi, I'm looking to use svelty picker with a custom trigger element. (For example - a button that you can save the picked date in your own component).

I've tried this sort of setup to accomplish this with the current implementation to no success:

```
				<SveltyPicker
					inputClasses="!w-0 !h-0 !p-0 !border-none"
					initialDate={date}
					bind:inputElement={elemInput}
				/>
				<div class="h-0 w-0 overflow-hidden">
					<input bind:this={elemInput} tabindex="-1" on:click={() => console.log('hello world')} />
				</div>

```

**Comment by mskocik** [comment]
There is an [example](https://svelte.dev/repl/b1a5432c3e8f4115947d2b639f6dc9bc?version=4.0.5) that might show you (hopefully) the way to implement what you want.
