### ISSUE TITLE
Conversion to date

### ISSUE THREAD

**Issue by phasianus** [mskocik/svelty-picker#99]
Thanks for your good work.

I have english and german date format, but I need generic js-date, not strings, how can I parse `value` back to js-date? `onChange` event should pass js-date as parameter, seems to me.

**Comment by mskocik** [comment]
You can achieve this by using `parseDate` function, which is also exported from lib.

Here is [simple example](https://svelte.dev/repl/63fb2d678e8e4460a3a9eec1d1e132d8?version=3.59.1), how you can achieve this.
